In [15]:
import numpy as np
import pandas

In [3]:
arr=np.array([1,2,3])

In [4]:
np.save("mysimplerarr",arr)

In [7]:
np.load("mysimplerarr.npy")

array([1, 2, 3])

In [8]:
np.savez("myarrs.npz",arr1=arr,arr2=np.array(["giza","cairo"]))

In [11]:
np.load("myarrs.npz")["arr2"]

array(['giza', 'cairo'],
      dtype='<U5')

In [13]:
np.savetxt("marrtext.txt",arr,delimiter=",")

In [14]:
np.loadtxt("marrtext.txt")

array([ 1.,  2.,  3.])

In [19]:
pandas.read_excel(io=r"C:\Users\Mo Ragheb\Downloads\Data minings\2-bundesliga 2019.xlsx").as_matrix()

array([[1, 'Bochum', 'VS', ..., nan, nan, nan],
       [2, 'Sandhausen', 'VS', ..., nan, nan, nan],
       [3, 'St. Pauli', 'VS', ..., nan, nan, nan],
       ..., 
       [295, 'SG Dynamo Dresden', 'VS', ..., nan, nan, nan],
       [296, 'Stuttgart', 'VS', ..., nan, nan, nan],
       [297, 'Wehen', 'VS', ..., nan, nan, nan]], dtype=object)