In [24]:
import numpy as np

In [52]:
l=[1,2,3,4,5]
l2=[6,7,8,9]

In [67]:
array1=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float)

In [86]:
array1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [69]:
array1*2

array([[  2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.]])

In [70]:
5/array1

array([[ 5.        ,  2.5       ,  1.66666667,  1.25      ],
       [ 1.        ,  0.83333333,  0.71428571,  0.625     ]])

In [71]:
array1.dtype

dtype('float64')

In [42]:
onearr=np.ones(5)
zeroarr=np.zeros([5,5])
onearr
zeroarr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [40]:
identityarr=np.identity(3,np.int)

In [41]:
identityarr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [73]:
tarr=np.arange(5,50,5)

In [74]:
help(np.identity)

Help on function identity in module numpy.core.numeric:

identity(n, dtype=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[ 1.,  0.,  0.],
           [ 0.,  1.,  0.],
           [ 0.,  0.,  1.]])



In [77]:
tarr[::-1]

array([45, 40, 35, 30, 25, 20, 15, 10,  5])

In [79]:
tarr[0]=20

In [83]:
tarr

array([20, 10, 15, 20, 25, 30, 35, 40, 45])

In [84]:
sliceoftarr=tarr[0:4]
sliceoftarr[:]=99
tarr

array([99, 99, 99, 99, 25, 30, 35, 40, 45])

In [85]:
sliceoftarr

array([99, 99, 99, 99])

In [88]:
array1[1,1]

6.0

In [107]:
multidarray=np.array(([1,2,3],[10,100,100],[-1,-2,-3]))

In [108]:
multidarray

array([[  1,   2,   3],
       [ 10, 100, 100],
       [ -1,  -2,  -3]])

In [109]:
multidarray[1:,0:2]

array([[ 10, 100],
       [ -1,  -2]])

In [110]:
multidarray[0,0:]=9

In [119]:
multidarray

array([[  9,   9,   9],
       [ 10, 100, 100],
       [ -1,  -2,  -3]])

In [143]:
shaper=np.arange(50).reshape(10,5)

In [144]:
shaper

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [145]:
np.dot(shaper,shaper.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [146]:
shaper

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [147]:
shaper.swapaxes(0,1)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [152]:
shaper[0,0:]=shaper[0:5,3]

In [153]:
shaper

array([[23,  8, 13, 18, 23],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [158]:
arr_3d = np.arange(50).reshape(2,5,5)

In [160]:
arr_3d.swapaxes(0,2)

array([[[ 0, 25],
        [ 5, 30],
        [10, 35],
        [15, 40],
        [20, 45]],

       [[ 1, 26],
        [ 6, 31],
        [11, 36],
        [16, 41],
        [21, 46]],

       [[ 2, 27],
        [ 7, 32],
        [12, 37],
        [17, 42],
        [22, 47]],

       [[ 3, 28],
        [ 8, 33],
        [13, 38],
        [18, 43],
        [23, 48]],

       [[ 4, 29],
        [ 9, 34],
        [14, 39],
        [19, 44],
        [24, 49]]])

In [162]:
np.exp(arr_3d)

array([[[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
           2.00855369e+01,   5.45981500e+01],
        [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
           2.98095799e+03,   8.10308393e+03],
        [  2.20264658e+04,   5.98741417e+04,   1.62754791e+05,
           4.42413392e+05,   1.20260428e+06],
        [  3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
           6.56599691e+07,   1.78482301e+08],
        [  4.85165195e+08,   1.31881573e+09,   3.58491285e+09,
           9.74480345e+09,   2.64891221e+10]],

       [[  7.20048993e+10,   1.95729609e+11,   5.32048241e+11,
           1.44625706e+12,   3.93133430e+12],
        [  1.06864746e+13,   2.90488497e+13,   7.89629602e+13,
           2.14643580e+14,   5.83461743e+14],
        [  1.58601345e+15,   4.31123155e+15,   1.17191424e+16,
           3.18559318e+16,   8.65934004e+16],
        [  2.35385267e+17,   6.39843494e+17,   1.73927494e+18,
           4.72783947e+18,   1.28516001e+19],
        [  3.4934

In [161]:
np.sqrt(arr_3d)

array([[[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
        [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
        [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
        [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894],
        [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949]],

       [[ 5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481],
        [ 5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189],
        [ 5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ],
        [ 6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958],
        [ 6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ]]])

In [180]:
rand1=np.random.randn(10,2)
rand2=np.random.randn(10,2)

In [181]:
np.maximum(rand1,rand2)

array([[-0.06303415,  1.57716587],
       [ 0.93430707,  1.85851363],
       [ 0.1583206 ,  0.98939536],
       [ 0.06274056,  1.55878891],
       [-0.44629725,  1.37495211],
       [-0.67757459, -0.39873943],
       [-0.50845264,  1.00365718],
       [-0.19510036,  0.72754189],
       [ 1.62073908,  0.87642035],
       [ 0.15273335,  0.26330754]])

In [182]:
np.conjugate(rand1,rand2)

array([[ -2.69460359e-01,   1.57716587e+00],
       [  9.34307075e-01,   1.15092591e+00],
       [ -7.79158875e-01,   9.89395361e-01],
       [ -1.24028027e+00,   1.45427668e+00],
       [ -8.38874871e-01,   1.37495211e+00],
       [ -9.72606349e-01,  -1.50272591e+00],
       [ -5.08452636e-01,  -9.54541471e-01],
       [ -1.95100360e-01,  -2.09721382e+00],
       [  1.62073908e+00,   8.76420351e-01],
       [ -4.41858302e-01,  -1.54377820e-05]])

In [184]:
np.rint(rand1)

array([[-0.,  2.],
       [ 1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1., -2.],
       [-1., -1.],
       [-0., -2.],
       [ 2.,  1.],
       [-0., -0.]])

In [ ]:
np.conjugate(rand1,rand2)

In [176]:
rand1

-41.511690865185265