In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
arr=np.arange(9).reshape(3,3)

In [4]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr,arr],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr,arr],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
ser1=Series([1,2,3],index=["T","U","V"])
ser2=Series(range(6,9,1),index=["X","Y","Z"])

In [17]:
pd.concat([ser1,ser2],keys=["key1","key2"],axis=1,ignore_index=True)

0    1
T  1.0  NaN
U  2.0  NaN
V  3.0  NaN
X  NaN  6.0
Y  NaN  7.0
Z  NaN  8.0

In [20]:
df1=DataFrame(np.random.randn(4,3),columns=["Z","X","C"])
df2=DataFrame(np.random.randn(3,3),columns=["S","A","Z"])

In [24]:
pd.concat([df1,df2],ignore_index=True)

A         C         S         X         Z
0       NaN  0.098990       NaN  1.221698 -0.111217
1       NaN  0.065419       NaN -0.958591 -1.512435
2       NaN  0.592266       NaN -0.308639  0.259141
3       NaN  0.262865       NaN -1.573173 -0.491872
4 -0.238333       NaN -0.008861       NaN  2.380900
5 -0.986683       NaN -1.314674       NaN -0.979794
6 -0.000729       NaN -0.694336       NaN  0.220774

In [25]:
sercombine=Series([2,np.nan,np.nan,4,5,np.nan],index=list("QUVXYZ"))

In [26]:
sercombine

Q    2.0
U    NaN
V    NaN
X    4.0
Y    5.0
Z    NaN
dtype: float64

In [34]:
ssercomvine1=Series(np.arange(len(sercombine)),dtype=np.float64,index=list("QUVXYZ"))
ssercomvine1

Q    0.0
U    1.0
V    2.0
X    3.0
Y    4.0
Z    5.0
dtype: float64

In [33]:
np.where(pd.isnull(sercombine),ssercomvine1,sercombine)

array([ 2.,  1.,  2.,  4.,  5.,  5.])

In [35]:
sercombine.combine_first(ssercomvine1)

Q    2.0
U    1.0
V    2.0
X    4.0
Y    5.0
Z    5.0
dtype: float64

In [37]:
dframe_odds = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
dframe_evens = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

In [39]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN